process SNPEFF_ANNOTATE {
    publishDir "$params.DEFAULT.outdir/annotation/snpeff", mode: 'copy'
    errorStrategy 'finish'
    cpus params.snpeff_annotate.cluster_cpus
    memory params.snpeff_annotate.cluster_memory
    time params.snpeff_annotate.cluster_time

    input:
        // Per-sample filtered VCF from VARCAP_UNIFY_GI_CHROM_NAMES.
        tuple val(sample_id), path(vcf_file)
        // Compiled snpEff DB workspace (contains data/<genome_id>/ binaries).
        path(db_dir)
        // snpEff.config augmented with our genome entry; passed via -c.
        path(snpeff_config)
        // One-line file containing the genome ID key used in snpEff.config.
        path(genome_id_file)

    output:
        // Annotated VCF with ANN fields added by snpEff.
        tuple val(sample_id), path("${sample_id}.eff.vcf"), emit: annotated_vcf
        // HTML summary report generated by snpEff (per-sample stats).
        tuple val(sample_id), path("${sample_id}_snpEff_summary.html"), emit: summary_html
        // Plain-text gene summary table (counts of effects per gene).
        tuple val(sample_id), path("${sample_id}_snpEff_summary.genes.txt"), emit: genes_txt

    script:
        """
        normalize_chrom() {
            printf "%s\n" "\$1" | cut -d '.' -f1 | tr -d '\n'
        }

        # Read genome ID from the single-line file emitted by SNPEFF_BUILD_DB.
        # This must match the key written into snpEff.config (e.g. Pseud_AE27_CP146966).
        genome_id=\$( cat ${genome_id_file} )

        # Normalize accession-version suffixes in the VCF only for snpEff.
        # Example: CP146966.1 -> CP146966
        while IFS= read -r line; do
            if [[ \$line == '##contig=<ID='* ]]; then
                contig_id=\$(printf "%s\\n" "\$line" | sed -E 's/^##contig=<ID=([^,>]+).*/\\1/')
                normalized_id=\$(normalize_chrom "\$contig_id")
                printf "%s\\n" "\$line" | sed -E "s/^##contig=<ID=[^,>]+/##contig=<ID=\$normalized_id/"
            elif [[ \$line == \\#* ]]; then
                printf "%s\\n" "\$line"
            else
                chrom=\$(printf "%s\\n" "\$line" | cut -f1)
                rest=\$(printf "%s\\n" "\$line" | cut -f2-)
                chrom=\$(normalize_chrom "\$chrom")
                printf "%s\\t%s\\n" "\$chrom" "\$rest"
            fi
        done < ${vcf_file} > ${sample_id}.snpeff_input.vcf

        # Run snpEff functional annotation.
        # eff:    annotate mode (adds ANN= field to each VCF record)
        # -c:     path to our generated config (contains genome entry + codon table refs)
        # -i vcf: input format
        # -o vcf: output format
        # -ud 0:  upstream/downstream effect window = 0 bp
        #         (only report variants that fall within annotated features;
        #          for a compact microbial genome this avoids spurious hits)
        # -v:     verbose; helps diagnose annotation issues
        # -stats: write per-sample HTML summary and gene table to named files
        # The genome_id positional argument selects which DB entry to use.
        java -Xmx${params.snpeff_annotate.java_xmx} \
            -jar /app_home/snpEff/snpEff.jar eff \
            -c ${snpeff_config} \
            -i vcf \
            -o vcf \
            -ud ${params.snpeff_annotate.upstream_downstream} \
            -v \
            -stats ${sample_id}_snpEff_summary.html \
            "\${genome_id}" \
            ${sample_id}.snpeff_input.vcf \
            > ${sample_id}.eff.vcf
        """
}
